name: file_organizer
description: A Windows command-line tool to organize files by extension.
version: 1.0.0

environment:
  sdk: "^3.1.0"

dependencies:
  win32: ^5.1.1
  args: ^2.4.2
  path: ^1.8.0
  cli_progress_bar: ^1.0.0
  colorize: ^3.0.0
  console: ^4.1.0
  archive: ^3.4.9
  logging: ^1.2.0
